### ISSUE TITLE
QuickMfluxNode save_images_with_metadata() got an unexpected keyword argument 'image_strength'

### ISSUE THREAD

**Issue by Bavoch** [filipstrand/mflux#104]
![image](https://github.com/user-attachments/assets/ac416728-e8fd-4839-8248-dd3cb9243fda)

**Comment by raysers** [comment]
Hi, @Bavoch, this is my mistake. The issue is with the ComfyUI plugin. You can try providing feedback in the plugin's repository. For now, you can disable the metadata button. I've been quite busy recently, but I'll find time to check and resolve it.

**Comment by Bavoch** [comment]
> Hi, @Bavoch, this is my mistake. The issue is with the ComfyUI plugin. You can try providing feedback in the plugin's repository. For now, you can disable the metadata button. I've been quite busy recently, but I'll find time to check and resolve it.

Thank you for the prompt response and clarification. I appreciate your efforts to look into this issue despite your busy schedule. I'll follow your advice regarding the plugin feedback. Looking forward to your update.

**Comment by raysers** [comment]
@Bavoch Sorry for keeping you waiting. I just fixed it, and I sincerely apologize for the inconvenience caused over the past few days. Could you please test it to see if it's working properly now?

**Comment by Bavoch** [comment]
> @Bavoch Sorry for keeping you waiting. I just fixed it, and I sincerely apologize for the inconvenience caused over the past few days. Could you please test it to see if it's working properly now?

Thank you for your hard work. It’s working fine now, thank you!
