### ISSUE TITLE
Performance report - 2023 M3 Pro 36GB

### ISSUE THREAD

**Issue by kush-gupt** [filipstrand/mflux#11]
Thanks for making my Mac a high quality image generating machine!

> python main.py --prompt "Luxury food photograph" --steps 2 --seed 2 --height   9.66s user 34.91s system 54% cpu 1:21.85 total
> ![image](https://github.com/user-attachments/assets/13ae90e6-9977-47d9-8af9-5e3cf754fe97)

**Comment by AaronWard** [comment]
Same specs here. so happy to finally have this working on my mac - great work @filipstrand 

![image(1)](https://github.com/user-attachments/assets/27c514fb-19f4-4169-a1e5-e8451d32cdb0)

**Comment by filipstrand** [comment]
@kush-gupt Thanks! Will add your numbers to the report table. 

@AaronWard Thank you and happy that you like it :)
