### ISSUE TITLE
Performance Report - 2020 M1 Air 8GB

### ISSUE THREAD

**Issue by mbvillaverde** [filipstrand/mflux#13]
Hi! Thank you for this awesome project. I managed to create some images even with small amount of RAM in my machine.
I had to change some values with the dimension and performed the command with Chrome and VSCode open and below are my results:

```
python main.py --prompt "detailed cinematic dof render of an old dusty detailed CRT monitor on a wooden desk in a dim room with items around, messy dirty room. On the screen are the letters 'mFLUX' glowing softly. High detail hard surface render" --height 512 --width 512
```

```
Fetching 8 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 23513.97it/s]
Fetching 7 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 66727.56it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [05:35<00:00, 83.91s/it]
```

**Output:**
![image2](https://github.com/user-attachments/assets/2fdebb7a-c55e-48c3-86c5-3c3fe35272fc)

**Activity Monitor:**
![SCR-20240821-hxqu](https://github.com/user-attachments/assets/77eccdce-e509-47eb-830b-c6c158591a2d)

**Comment by filipstrand** [comment]
@mbvillaverde Very cool that you got it working on your 8GB Air! Now I start to wonder if this will actually run on a modern iPhone :) 

I will include your numbers in the report table with the additional info that you scaled down the image.

**Comment by 4external** [comment]
@mbvillaverde Hi! Can you provide please instructions how you run on mba-8GB? It's standard flow from doc from this repo?
