### ISSUE TITLE
Support for Gradio WebUI

### ISSUE THREAD

**Issue by 7enChan** [filipstrand/mflux#15]
I would like to propose adding support for Gradio WebUI to this project. The current terminal input experience is not very user-friendly. Gradio could significantly enhance the usability and accessibility of our project.
I have implemented a version using cursor, but as I'm not very familiar with coding, I'm unsure if this code is sufficiently concise and elegant. Therefore, I'm not submitting a pull request. Instead, I've attached the code to this issue for reference.
To use this implementation, you need to install the following dependency

`pip install gradio`

![SCR-20240821-mvnv](https://github.com/user-attachments/assets/020cf6f8-83bf-47c1-b292-e4c1171f720c)

[gradioui.py.zip](https://github.com/user-attachments/files/16686922/gradioui.py.zip)

**Comment by emilune** [comment]
Hello. I'm a newbie. Can you explain how use it ? thanks in advance.

**Comment by filipstrand** [comment]
It would indeed be nice to have support for a frontend like Gradio or something similar. If I remember correctly, the original FLUX repo from Black Forest Labs had Streamlit as a frontend to interact with the model. Will put this on the todo list!

**Comment by 7enChan** [comment]
> Hello. I'm a newbie. Can you explain how use it ? thanks in advance.

This is just a demo. It's recommended to wait for @filipstrand's more complete version. If you insist on using it now, you can follow these steps:
1. I assume you can already run mflux normally.
2. In the window where you run mflux, enter pip install gradio to install gradio, as this interface is built using gradio.
3. Download the gradiui.py file I provided in the attachment(need to unzip), place it in your mflux root directory, then at the terminal run: python gradiui.py
4. After successful execution, your terminal will display an address, usually http://127.0.0.1:7860 Open it in your browser and enjoy.

My English is not very good, the above was translated with the help of AI, I hope it can be described clearly.

**Comment by 7enChan** [comment]
> It would indeed be nice to have support for a frontend like Gradio or something similar. If I remember correctly, the original FLUX repo from Black Forest Labs had Streamlit as a frontend to interact with the model. Will put this on the todo list!

I've looked into Streamlit and found that its interface is indeed more elegant, though it's also a bit more complex to implement. Black Forest Labs has provided two demos, conveniently based on Gradio and Streamlit. Whichever one is used, support for either would be exciting.

**Comment by emilune** [comment]
Thanks for your answer.
I tried to add “import gradioui” in main.py file and it worked.

> > Hello. I'm a newbie. Can you explain how use it ? thanks in advance.
> 
> This is just a demo. It's recommended to wait for @filipstrand's more complete version. If you insist on using it now, you can follow these steps:
> 
> 1. I assume you can already run mflux normally.
> 2. In the window where you run mflux, enter pip install gradio to install gradio, as this interface is built using gradio.
> 3. Download the gradiui.py file I provided in the attachment(need to unzip), place it in your mflux root directory, then at the terminal run: python gradiui.py
> 4. After successful execution, your terminal will display an address, usually http://127.0.0.1:7860 Open it in your browser and enjoy.
> 
> My English is not very good, the above was translated with the help of AI, I hope it can be described clearly.

Thanks for your answer.
I tried to add “import gradioui” in main.py and it worked.

**Comment by emilune** [comment]
> Thanks for your answer. I tried to add “import gradioui” in main.py file and it worked.
> 
> > > Hello. I'm a newbie. Can you explain how use it ? thanks in advance.
> > 
> > 
> > This is just a demo. It's recommended to wait for @filipstrand's more complete version. If you insist on using it now, you can follow these steps:
> > 
> > 1. I assume you can already run mflux normally.
> > 2. In the window where you run mflux, enter pip install gradio to install gradio, as this interface is built using gradio.
> > 3. Download the gradiui.py file I provided in the attachment(need to unzip), place it in your mflux root directory, then at the terminal run: python gradiui.py
> > 4. After successful execution, your terminal will display an address, usually http://127.0.0.1:7860 Open it in your browser and enjoy.
> > 
> > My English is not very good, the above was translated with the help of AI, I hope it can be described clearly.
> 
> Thanks for your answer. I tried to add “import gradioui” in main.py and it worked.

With python main.py

**Comment by 7enChan** [comment]
I have implemented a WebUI using Streamlit. The design philosophy is to have an ultra-minimalist mode that focuses entirely on the Prompt. Since I added some other features to this version, it requires changes to multiple files, so I won't be sharing it.
For example, it supports the dev&schnell merged model, as well as a magic prompt feature (implemented through Gemini or Groq API). Because my English isn't very good, the magic prompt can convert user prompts from almost any language into English and optimize them into prompts suitable

<img width="1644" alt="SCR-20240823-rgkp" src="https://github.com/user-attachments/assets/b16b0c9f-391f-4875-a665-c049e3d0c3dd">
 for FLUX.
<img width="1638" alt="SCR-20240823-rggv" src="https://github.com/user-attachments/assets/ed412569-547a-4be4-b503-4d4449f58d8c">

![SCR-20240823-rhfa](https://github.com/user-attachments/assets/1e649074-3a6f-4413-bf3e-9eb5f70e2d4f)

**Comment by raysers** [comment]
非常好的工作。如果有可能，是否可以尝试实现COMFYUI的移植？

**Comment by anthonywu** [comment]
I've started a [FastHTML](http://fastht.ml)-based web app here: https://github.com/anthonywu/mflux-fasthtml - limited functionality coverage, visually basic, not ready to advertise widely, but FYI in case anyone with dev interest want to help out.

<img width="1051" alt="image" src="https://github.com/user-attachments/assets/1096d5a2-7d6d-465c-9800-70549a964cd0">

**Comment by filipstrand** [comment]
@anthonywu Very nice! I remember hearing about FastHTML a while back but never tried it out

**Comment by elitexp** [comment]
<img width="871" alt="image" src="https://github.com/user-attachments/assets/ba0d7b24-4b79-409f-93ff-6edfb306b353">

**Comment by anthonywu** [comment]
The more the merrier, love to see it. I'll check it out and I think from the various UIs we can find some common utils consolidate downwards into the library.

I also see an opportunity to generalize new UI attempts to be provider-agnostic e.g. just take a generator callable.

I had also considered a Marimo or Jupyter notebook front-end for "researcher" or "eval" personas.

**Comment by filipstrand** [comment]
@elitexp Very nice! I recently added a [related projects](https://github.com/filipstrand/mflux?tab=readme-ov-file#-related-projects) section in the README, will add your project there too!
