### ISSUE TITLE
4-bit

### ISSUE THREAD

**Issue by okaneyo** [filipstrand/mflux#18]
More compression

**Comment by filipstrand** [comment]
@okaneyo Great suggestion! Have not really investigated this myself yet, but looking around this seems really promising. For example, it looks like https://github.com/argmaxinc/DiffusionKit have recently added 4bit support for Flux. I have added this to the todo list!

**Comment by filipstrand** [comment]
@okaneyo [This feature has now been added to the project](https://github.com/filipstrand/mflux?tab=readme-ov-file#quantization). Let me know if something does not work as expected!

**Comment by n0kovo** [comment]
More compression
