### ISSUE TITLE
Where does it download the model ?

### ISSUE THREAD

**Issue by dostarora97** [filipstrand/mflux#20]
Could you please specify in the README description where does the code download the model

**Comment by filipstrand** [comment]
I am sure you can change this somewhere (I think changing the `HF_HOME` variable can control this https://huggingface.co/docs/huggingface_hub/en/package_reference/environment_variables), but by default it downloads the model in the `.cache` folder in your home directory. So, in my case, it would be something like:   

`/Users/filipstrand/.cache/huggingface/hub/models--black-forest-labs--FLUX.1-dev`

I can add this to the readme for clarification.
