### ISSUE TITLE
Why GPU usage is low?

### ISSUE THREAD

**Issue by smoothdvd** [filipstrand/mflux#25]
python main.py --model dev --prompt "Luxury food photograph" --steps 25 --seed 2

<img width="1421" alt="Screenshot 2024-09-01 at 6 51 38 PM" src="https://github.com/user-attachments/assets/6598e16e-fc24-4e98-b8af-6fb8ade875cc">

**Comment by filipstrand** [comment]
Hi @smoothdvd , my guess is that you are memory limited. 

Have you tried running the model in  `-q 8` or `-q 4` mode? For example:

```
python main.py --model schnell --prompt "Luxury food photograph" --steps 2 --seed 2 -q 8
```

**Comment by smoothdvd** [comment]
@filipstrand You are right! Thank you for your help.
