### ISSUE TITLE
Feature Request: Show Prompt Metadata in Get Info

### ISSUE THREAD

**Issue by vincyb** [filipstrand/mflux#26]
I have a quick suggestion for the Flux MLX project. It would be awesome if the "Get Info" window for generated images could display some key metadata like: Prompt, Seed, CFG Guidance, Model, or even time it took to generate.
Having this info readily available would make it easier for users to manage and reproduce their work without digging separate logs. 

I think 'Getinfo' in finder or in Preview app show inspector can easily display meta data, such as 'keywords' embedded text via IPTC or exif xml

**Comment by filipstrand** [comment]
@vincyb Great idea. I have also briefly thought about the idea of exporting metadata along with an image, but I was thinking something more primitive like exporting a json file or similar. Your suggestion is much more elegant, will add this feature soon!

**Comment by filipstrand** [comment]
This feature is now in main! Could not get it to work in the  "Get Info" window, but at least the internal refactoring in the project will make it easier to add this in the future. 

I use a tool like `exiftool` to inspect the metadata

 ```
 exiftool image.png
 ```
 
There is also an option to save this to disk by passing in the `--metadata` flag. The metadata file will be named the same as the image.
