### ISSUE TITLE
Question about generation speed

### ISSUE THREAD

**Issue by TuiKiken** [filipstrand/mflux#33]
Hi! Can someone explain why different tools using the same models show dramatically different results? I tried generating images using Draw Things and mflux with the same settings and prompt and got the following results:
- Draw Things: ~1m20s
- mflux with -q 8 setting: ~3m30s
- mflux without -q setting: ~7m

I have a weak laptop (MacBook 2021, M1 Pro, 16GB), but the difference in performance is significant. Maybe I make something wrong?
Thank you.

**Comment by filipstrand** [comment]
@TuiKiken Hi. I have not looked into `Draw Things` but it is indeed impressive on their end if the difference is that large for similar settings. The generation speed depends on a few factors, such as the hardware, image resolution, quantization etc. The more RAM available the faster it will run (so closing other application in the background can help). If maxing out the memory it will typically resort to swap memory (disk storage) which slows things down.
