### ISSUE TITLE
Where do I need to place the Lora file for it to work as shown in the examples?

### ISSUE THREAD

**Issue by meetbryce** [filipstrand/mflux#39]
I tried a few places with no luck. Thanks in advance!

![Screenshot 2024-09-07 at 18 32 06@2x](https://github.com/user-attachments/assets/640875f8-c9ad-4d9d-bfd7-61259ebfec8e)

**Comment by anthonywu** [comment]
the paths must be resolvable from the `pwd` of where you ran the command as shown in the report.

quick check:

- before you run the `mflux-generate` again, do `pwd` to double check where you are, then `ls $the_lora_path_param` to make sure `ls` finds the file.

You're probably just not in the directory you think you're in.

**Comment by meetbryce** [comment]
thanks! i'm a genius and switched - and _
