### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ckizer** [filipstrand/mflux#41]
No matter how hard I try or what packages I install, and --force uninstall, and ignore installed. It won't let me download the packages from pip. AI can't figure it out either

```
llected packages: wcwidth, sortedcontainers, mpmath, xmod, urllib3, tzdata, typing-extensions, tqdm, tenacity, sympy, sniffio, six, safetensors, regex, readchar, pyyaml, python-dotenv, pysocks, psutil, packaging, orjson, numpy, networkx, mypy-extensions, multidict, MarkupSafe, jsonpointer, jiter, idna, h11, fsspec, frozenlist, filelock, distro, charset-normalizer, certifi, attrs, annotated-types, aiohappyeyeballs, yarl, wsproto, typing-inspect, SQLAlchemy, runs, requests, pydantic-core, outcome, marshmallow, jsonpatch, jinja2, httpcore, faiss-cpu, blessed, anyio, aiosignal, webdriver-manager, trio, torch, tiktoken, pydantic, huggingface-hub, httpx, editor, dataclasses-json, aiohttp, trio-websocket, openai, langsmith, inquirer, accelerate, selenium, langchain-core, langchain-text-splitters, langchain-openai, langchain, langchain-community, lib-resume-builder-aihawk
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-interpreter 0.1.0 requires openai<0.28.0,>=0.27.8, but you have openai 1.44.0 which is incompatible.
open-interpreter 0.1.0 requires tiktoken<0.5.0,>=0.4.0, but you have tiktoken 0.7.0 which is incompatible.
torchaudio 2.4.0 requires torch==2.4.0, but you have torch 2.4.1 which is incompatible.
tokentrim 0.1.6 requires tiktoken<0.5.0,>=0.4.0, but you have tiktoken 0.7.0 which is incompatible.
spaces 0.29.3 requires psutil<6,>=2, but you have psutil 6.0.0 which is incompatible.
torchvision 0.19.0 requires torch==2.4.0, but you have torch 2.4.1 which is incompatible.
Successfully installed MarkupSafe-2.1.5 SQLAlchemy-2.0.34 accelerate-0.33.0 aiohappyeyeballs-2.4.0 aiohttp-3.10.5 aiosignal-1.3.1 annotated-types-0.7.0 anyio-4.4.0 attrs-24.2.0 blessed-1.20.0 certifi-2024.8.30 charset-normalizer-3.3.2 dataclasses-json-0.6.7 distro-1.9.0 editor-1.6.6 faiss-cpu-1.8.0.post1 filelock-3.16.0 frozenlist-1.4.0 fsspec-2024.9.0 h11-0.14.0 httpcore-1.0.5 httpx-0.27.2 huggingface-hub-0.24.6 idna-3.8 inquirer-3.1.3 jinja2-3.1.4 jiter-0.5.0 jsonpatch-1.33 jsonpointer-3.0.0 langchain-0.2.16 langchain-community-0.2.16 langchain-core-0.2.38 langchain-openai-0.1.23 langchain-text-splitters-0.2.2 langsmith-0.1.93 lib-resume-builder-aihawk-0.2 marshmallow-3.22.0 mpmath-1.3.0 multidict-6.0.4 mypy-extensions-1.0.0 networkx-3.3 numpy-1.26.4 openai-1.44.0 orjson-3.10.7 outcome-1.3.0.post0 packaging-24.1 psutil-6.0.0 pydantic-2.9.0 pydantic-core-2.23.2 pysocks-1.7.1 python-dotenv-1.0.1 pyyaml-6.0.2 readchar-4.2.0 regex-2024.7.24 requests-2.32.3 runs-1.2.2 safetensors-0.4.4 selenium-4.9.1 six-1.16.0 sniffio-1.3.1 sortedcontainers-2.4.0 sympy-1.13.2 tenacity-8.5.0 tiktoken-0.7.0 torch-2.4.1 tqdm-4.66.5 trio-0.26.2 trio-websocket-0.11.1 typing-extensions-4.12.2 typing-inspect-0.9.0 tzdata-2024.1 urllib3-2.2.2 wcwidth-0.2.6 webdriver-manager-4.0.2 wsproto-1.2.0 xmod-1.8.1 yarl-1.9.2
ck@StarlinkPro mflux-ai % 

```

**Comment by filipstrand** [comment]
Quickly looked at your output here and I see `mflux-ai` which is not our package. Have you tried with `pip install -U mflux`?

**Comment by ckizer** [comment]
> Quickly looked at your output here and I see `mflux-ai` which is not our package. Have you tried with `pip install -U mflux`?

This is what happens when I have to many GitHub repo windows open 😂 Thanks Filipstrand trying to get Mac flux to work so I can used my custom trained lora

**Comment by ckizer** [comment]
Actually my errors happen when I run your command from the front of your repo exactly "pip install -U mflux"
I may have installed other projects but I cant't get your repo working on Mac. I do have Mac ComfyUI running and uninstalled any of it's dependencies to try and get your repo working.

**Comment by ckizer** [comment]
`on ttys022
ck@StarlinkPro question-cards % pip install -U mflux
Collecting mflux
  Using cached mflux-0.2.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: mlx>=0.16.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from mflux) (0.17.2)
Collecting numpy>=2.0.0 (from mflux)
  Using cached numpy-2.1.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
Requirement already satisfied: pillow>=10.4.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from mflux) (10.4.0)
Requirement already satisfied: transformers>=4.44.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from mflux) (4.44.2)
Requirement already satisfied: sentencepiece>=0.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from mflux) (0.2.0)
Requirement already satisfied: torch>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from mflux) (2.4.1)
Requirement already satisfied: tqdm>=4.66.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from mflux) (4.66.5)
Requirement already satisfied: huggingface-hub>=0.24.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from mflux) (0.24.6)
Requirement already satisfied: safetensors>=0.4.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from mflux) (0.4.4)
Requirement already satisfied: piexif>=1.1.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from mflux) (1.1.3)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub>=0.24.5->mflux) (3.16.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub>=0.24.5->mflux) (2024.9.0)
Requirement already satisfied: packaging>=20.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub>=0.24.5->mflux) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub>=0.24.5->mflux) (6.0.2)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub>=0.24.5->mflux) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub>=0.24.5->mflux) (4.12.2)
Requirement already satisfied: sympy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch>=2.3.1->mflux) (1.13.2)
Requirement already satisfied: networkx in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch>=2.3.1->mflux) (3.3)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch>=2.3.1->mflux) (3.1.4)
Requirement already satisfied: regex!=2019.12.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers>=4.44.0->mflux) (2024.7.24)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers>=4.44.0->mflux) (0.19.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2->torch>=2.3.1->mflux) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface-hub>=0.24.5->mflux) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface-hub>=0.24.5->mflux) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface-hub>=0.24.5->mflux) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface-hub>=0.24.5->mflux) (2024.8.30)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from sympy->torch>=2.3.1->mflux) (1.3.0)
Using cached mflux-0.2.0-py3-none-any.whl (52 kB)
Using cached numpy-2.1.1-cp311-cp311-macosx_14_0_arm64.whl (5.4 MB)
Installing collected packages: numpy, mflux
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-community 0.2.16 requires numpy<2,>=1; python_version < "3.12", but you have numpy 2.1.1 which is incompatible.
faiss-cpu 1.8.0.post1 requires numpy<2.0,>=1.0, but you have numpy 2.1.1 which is incompatible.
accelerate 0.33.0 requires numpy<2.0.0,>=1.17, but you have numpy 2.1.1 which is incompatible.
langchain 0.2.16 requires numpy<2,>=1; python_version < "3.12", but you have numpy 2.1.1 which is incompatible.
spaces 0.29.3 requires psutil<6,>=2, but you have psutil 6.0.0 which is incompatible.
torchvision 0.19.0 requires torch==2.4.0, but you have torch 2.4.1 which is incompatible.
Successfully installed mflux-0.2.0 numpy-2.1.1
ck@StarlinkPro question-cards % 
`

I tried uninstalling on the conflicting versions of pip packages, reinstalling the exact version you require manually, but no dice.

**Comment by ckizer** [comment]
I'll give it a try now.
