### ISSUE TITLE
Fetching files freeze

### ISSUE THREAD

**Issue by filippkowalski** [filipstrand/mflux#42]
Hey,

first of all many thanks for creating this package 🙏

I've tried to run it for the past hour, but it seems that there is some issue with downloading some files.

It's stuck at the second step of downloading.

I'm not sure if the issue is that I've already tried to download some files but interrupted it and now it doesn't want to override them or there is some kind of connectivity issue or files are not accessible.

I did remove /huggingface cache directory but to no avail
![CleanShot 2024-09-08 at 11 09 52@2x](https://github.com/user-attachments/assets/a3ff7438-65e2-4d98-84f2-531569542452)

**Comment by filipstrand** [comment]
@filippkowalski Hi, sorry for the delayed response! Just curious, is this still a problem for you? I would have imagined removing the cache as you did, or simply a retry would have helped. Obviously we want automatic downloading to work, but as a last resort, there is also the option of [loading models directly from disk](https://github.com/filipstrand/mflux?tab=readme-ov-file#running-a-non-quantized-model-directly-from-disk). So you can always download them manually and point to them without using the huggingface cache.

**Comment by filippkowalski** [comment]
@filipstrand hey! no worries and thanks for the answer -- I didn't try to do it afterwards, so dunno, I might try later!
