### ISSUE TITLE
local path quantized model with lora not working?

### ISSUE THREAD

**Issue by AugustRush** [filipstrand/mflux#49]
weight = transWeight + lora_scale * (lora_b @ lora_a)
             ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ValueError: Shapes (3072,768) and (3072,3072) cannot be broadcast.

**Comment by filipstrand** [comment]
@AugustRush This is now merged to main and will be included in the upcoming release. An example can be found [here](https://github.com/filipstrand/mflux?tab=readme-ov-file#saving-a-quantized-version-to-disk)
