### ISSUE TITLE
Project needs a license

### ISSUE THREAD

**Issue by anthonywu** [filipstrand/mflux#54]
suggestions for license

- MIT
- Apache 2.0

TODOS:

- [ ] add `LICENSE` file
- [ ] add standard license info in `README.md`
- [ ] add `[project]` `license = {file = "LICENSE"}` in `pyproject.toml`

**Comment by filipstrand** [comment]
@anthonywu I went with the MIT license. [PR here](https://github.com/filipstrand/mflux/pull/65) if you want to have a quick look :)
