### ISSUE TITLE
Performance report - 2023 M2 Max 96GB

### ISSUE THREAD

**Issue by explorigin** [filipstrand/mflux#6]
(Using my CLI options [here](https://github.com/filipstrand/mflux/pull/5) )

> time python main.py --prompt "Luxury food photograph" --steps 2 --seed 2  3.94s user 10.78s system 56% cpu 26.109 total
![image](https://github.com/user-attachments/assets/12be6576-eab7-4a44-9598-1a344fc6b125)

> time python main.py --prompt "detailed cinematic dof render of an old dusty detailed CRT monitor on a wooden desk in a dim room with items around, messy dirty room. On the screen are the letters "FLUX" glowing softly. High detail hard surface render" --steps 2 --seed 2  3.94s user 11.75s system 61% cpu 25.565 total
![image](https://github.com/user-attachments/assets/6788a498-a004-434e-8e8e-4842b97ec1a6)

So about 25-26 seconds.

**Comment by filipstrand** [comment]
@explorigin Thanks for the report (and nice picture with the food for --seed 2 :) ). I have looked at your PR and will include this performance result and some other numbers in the README once this PR is merged.

**Comment by 7enChan** [comment]
> (Using my CLI options [here](https://github.com/filipstrand/mflux/pull/5) )
> 
> > time python main.py --prompt "Luxury food photograph" --steps 2 --seed 2  3.94s user 10.78s system 56% cpu 26.109 total
> > ![image](https://private-user-images.githubusercontent.com/697818/358854865-12be6576-eab7-4a44-9598-1a344fc6b125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTczNzksIm5iZiI6MTcyNDE1NzA3OSwicGF0aCI6Ii82OTc4MTgvMzU4ODU0ODY1LTEyYmU2NTc2LWVhYjctNGE0NC05NTk4LTFhMzQ0ZmM2YjEyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxMjMxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzI2ZDI5ZjBhMDRkOGNhY2UyNjE5MjhiMDg2NGE1N2YyYWViODU4MmYzYTFhOGU4NzZkNGMzZDRjYjVlMmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0mEx7Fv0ZVXnj_mK8ybqAlP5S7B-lfY8lm7-JFNJfLM)
> 
> > time python main.py --prompt "detailed cinematic dof render of an old dusty detailed CRT monitor on a wooden desk in a dim room with items around, messy dirty room. On the screen are the letters "FLUX" glowing softly. High detail hard surface render" --steps 2 --seed 2  3.94s user 11.75s system 61% cpu 25.565 total
> > ![image](https://private-user-images.githubusercontent.com/697818/358854930-6788a498-a004-434e-8e8e-4842b97ec1a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTczNzksIm5iZiI6MTcyNDE1NzA3OSwicGF0aCI6Ii82OTc4MTgvMzU4ODU0OTMwLTY3ODhhNDk4LWEwMDQtNDM0ZS04ZThlLTQ4NDJiOTdlYzFhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxMjMxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWNiODAyNTJhZTU0ZjliOGI5OTU0MGRjZjM3YzEzMjc0Njk3ODM1NWZkMDAxNWY1YzA0M2FkN2I3ZjY0ZDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6hYievzwNqnVZP3IqcM-Q1xIVUKwhfmA9FfLK9PjOWM)
> 
> So about 25-26 seconds.

On the same machine (M2 Max 96GB MBP), the same prompt takes about 8 seconds longer to complete. I'm not sure what the reason is. I'm running this within a conda virtual environment with python 3.12.4

time python main.py --prompt "Luxury food photograph" --steps 2 --seed 2
Fetching 8 files: 100%|███████████████████████| 8/8 [00:00<00:00, 124737.67it/s]
Fetching 7 files: 100%|█████████████████████████| 7/7 [00:00<00:00, 9670.66it/s]
100%|█████████████████████████████████████████████| 2/2 [00:27<00:00, 13.83s/it]
python main.py --prompt "Luxury food photograph" --steps 2 --seed 2  4.19s user 12.84s system 49% cpu 34.180 total


time python main.py --prompt "detailed cinematic dof render of an old dusty detailed CRT monitor on a wooden desk in a dim room with items around, messy dirty room. On the screen are the letters "FLUX" glowing softly. High detail hard surface render" --steps 2 --seed 2
Fetching 8 files: 100%|███████████████████████| 8/8 [00:00<00:00, 127100.12it/s]
Fetching 7 files: 100%|████████████████████████| 7/7 [00:00<00:00, 74518.09it/s]
100%|█████████████████████████████████████████████| 2/2 [00:28<00:00, 14.00s/it]
python main.py --prompt  --steps 2 --seed 2  4.26s user 13.21s system 49% cpu 35.015 total

**Comment by explorigin** [comment]
There could be a loading time difference. Let's compare a few more things:
- virtualenv environment, Python 3.12.1
- Sonoma 14.6.1
- 4TB harddrive (APFS Encrypted)

**Comment by 7enChan** [comment]
> There could be a loading time difference. Let's compare a few more things:
> 
> * virtualenv environment, Python 3.12.1
> * Sonoma 14.6.1
> * 4TB harddrive (APFS Encrypted)

Thanks for the reply. Here is mine: 
* virtualenv environment, Python 3.12.4
* Sonoma 14.6.1
* 1TB harddrive (APFS Not encrypted)

**Comment by 7enChan** [comment]
> > There could be a loading time difference. Let's compare a few more things:
> > 
> > * virtualenv environment, Python 3.12.1
> > * Sonoma 14.6.1
> > * 4TB harddrive (APFS Encrypted)
> 
> Thanks for the reply. Here is mine:
> 
> * virtualenv environment, Python 3.12.4
> * Sonoma 14.6.1
> * 1TB harddrive (APFS Not encrypted)

Forgot one thing, I'm using the latest version of mflux

**Comment by explorigin** [comment]
Encryption also includes compression. For loading large models into memory, that might be the difference if the drive is the bottleneck. I'm speculating.

**Comment by 7enChan** [comment]
> Encryption also includes compression. For loading large models into memory, that might be the difference if the drive is the bottleneck. I'm speculating.

Interesting. If the drive is the bottleneck, then the time difference for FLUX.1 dev, which takes 20 steps, should be less.

**Comment by 7enChan** [comment]
> > Encryption also includes compression. For loading large models into memory, that might be the difference if the drive is the bottleneck. I'm speculating.
> 
> Interesting. If the drive is the bottleneck, then the time difference for FLUX.1 dev, which takes 20 steps, should be less.

I tried turning on encryption and it didn't take significantly less time, it was still around 34s 😂

**Comment by explorigin** [comment]
> I'm speculating

That leaves drive size as the remaining differentiator.

**Comment by 7enChan** [comment]
> > I'm speculating
> 
> That leaves drive size as the remaining differentiator.

Yeah, maybe the 4T harddrive doesn't have the same read/write speeds as 1T...
