### ISSUE TITLE
Performance report - 2021 M1 Pro 16GB

### ISSUE THREAD

**Issue by qw-in** [filipstrand/mflux#7]
(Using @explorigin's CLI options [here](https://github.com/filipstrand/mflux/pull/5))

> time python main.py --prompt "Luxury food photograph" --steps 2 --seed 2 175.80 sec total
image
> ![image](https://github.com/user-attachments/assets/2b25273b-41ca-445c-8aeb-d6af48bd5197)

Note that due to limited memory, swap had to be used (~22GB iirc). Running any other program at the same time will lock up and force reboot. Surprised it made it through at all tbh :)

**Comment by filipstrand** [comment]
@qw-in Thanks for checking this on a 16GB model! I was very curious about this one myself. On my 32GB machine, I also see some swapping (which was not the case for the smaller SD3 model for me as a comparison) and I think this slows down the generation time quite a bit. But very nice that it ran at all as you said :) 

I will add these reported numbers in the README along with some others soon.
