### ISSUE TITLE
Make binary adhere to signals

### ISSUE THREAD

**Issue by Morriz** [filipstrand/mflux#79]
Hi, `CTRL-C`'ing does not stop the binary right now. I can't stop a heavy gen and my laptop flies away ;p

**Comment by anthonywu** [comment]
This is done but just needs a new pypi release. #59 and #70 implements Ctrl-C handling. I can confirm that in the latest mflux installed from repo main, Ctrl-C will be respected.

@filipstrand can close this issue when 0.4.0+ is released.
