### ISSUE TITLE
Image generation speed for M4 Max Macbook Pro using mflux

### ISSUE THREAD

**Issue by kasnol** [filipstrand/mflux#92]
Just ran mflux in MacBook Pro 128Mb M4 Max Environment for reference, took sround 10.56s for image generation:

time mflux-generate \
--prompt "Luxury food photograph" \
--model schnell \
--steps 2 \
--seed 2 \
--height 1024 \
--width 1024

Fetching 8 files: 100%|████████████████████████| 8/8 [00:00<00:00, 14388.69it/s]
Fetching 7 files: 100%|█████████████████████████| 7/7 [00:00<00:00, 3499.84it/s]
100%|█████████████████████████████████████████████| 2/2 [00:15<00:00,  7.50s/it]
mflux-generate --prompt "Luxury food photograph" --model schnell --steps 2  2  1.88s user 10.56s system 32% cpu 38.232 total

**Comment by filipstrand** [comment]
Wow impressive! Can add this to the benchmark section. Just out of curiosity, if you run it quantized, by enabling the flag `--quantize 8`  or `--quantize 4` what numbers do you get?

**Comment by filipstrand** [comment]
Our benchmarks here are not very scientific and exact (still fun to have I think), but I looked through some of the old benchmark posts and there I tried to report the *total* time, so in your case that would be ~38 seconds I guess. Does that sound correct if you consider the total time it took from when you ran the command to when it finished?

**Comment by Stoobs** [comment]
Here's the result for the 14 core M4 Pro with 64GB in the new Mac mini:

time mflux-generate \
--prompt "Luxury food photograph" \
--model schnell \
--steps 2 \
--seed 2 \
--height 1024 \
--width 1024
Fetching 8 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 72628.64it/s]
Fetching 7 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 75865.96it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:29<00:00, 14.66s/it]
mflux-generate --prompt "Luxury food photograph" --model schnell --steps 2  2  1.91s user 15.96s system 51% cpu 34.701 total

**Comment by Stoobs** [comment]
Quantize 8:
time mflux-generate \
--prompt "Luxury food photograph" \
--model schnell \
--quantize 8 \
--steps 2 \
--seed 2 \
--height 1024 \
--width 1024
Fetching 8 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 78581.81it/s]
Fetching 7 files: 100%|████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 195734.19it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:29<00:00, 14.60s/it]
mflux-generate --prompt "Luxury food photograph" --model schnell --quantize 8  1.85s user 8.46s system 31% cpu 33.155 total

Quantize 4:
time mflux-generate \
--prompt "Luxury food photograph" \
--model schnell \
--quantize 4 \
--steps 2 \
--seed 2 \
--height 1024 \
--width 1024
Fetching 8 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 68338.97it/s]
Fetching 7 files: 100%|████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 158703.39it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:29<00:00, 14.65s/it]
mflux-generate --prompt "Luxury food photograph" --model schnell --quantize 4  1.90s user 8.28s system 30% cpu 33.598 total

It doesn't really seem to impact it that much?

**Comment by kasnol** [comment]
Hi @filipstrand , with the quantize flag 'on' it gives around ~7s, I turned on 'High Power Mode' in the 128Gb Apple M4 Max. 
 
time mflux-generate --prompt "Luxury food photograph" --model schnell --steps 2 --seed 2 --height 1024 --width 1024 --quantize 8
Fetching 8 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 96420.78it/s]
Fetching 7 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 9422.38it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:14<00:00,  7.36s/it]
mflux-generate --prompt "Luxury food photograph" --model schnell --steps 2  2  1.75s user 6.91s system 45% cpu 18.922 total

**Comment by kasnol** [comment]
Quantize 4 flag gives around ~7s for the M4 Max 128Gb too

time mflux-generate --prompt "Luxury food photograph" --model schnell --steps 2 --seed 2 --height 1024 --width 1024 --quantize 4
Fetching 8 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 118149.41it/s]
Fetching 7 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 7963.15it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:15<00:00,  7.85s/it]
mflux-generate --prompt "Luxury food photograph" --model schnell --steps 2  2  1.78s user 6.70s system 42% cpu 19.977 total

**Comment by filipstrand** [comment]
Before I close this ticket, @kasnol, just out of curiosity, I was curious again about your *total* numbers. When you ran

```
time mflux-generate
--prompt "Luxury food photograph"
--model schnell
--steps 2
--seed 2
--height 1024
--width 1024
``` 

i.e without any quantization, your total was `38.232 total`. On a repeated run, do you get similar values? (I guess I was expecting your setup to beat the M4 Pro with half the memory as provided by @Stoobs in this issue, but maybe there are other details that come into play here...) 

Just as a reference, [a similar setup to yours](https://gist.github.com/awni/a67d16d50f0f492d94a10418e0592bde?permalink_comment_id=5286033#gistcomment-5286033) get around 18 seconds for the non quantised run. 

I also just added a [command](https://github.com/filipstrand/mflux?tab=readme-ov-file#%EF%B8%8F-image-generation-speed-updated) in the README which you can run to find out the exact number of CPU/GPU cores on your machine.

**Comment by filipstrand** [comment]
@kasnol @Stoobs For the quantized runs, just like in in your examples, I have also noticed that there is basically no speedup when running the 4bit version compared to the 8bit one.

**Comment by kasnol** [comment]
actully 

> Before I close this ticket, @kasnol, just out of curiosity, I was curious again about your _total_ numbers. When you ran
> 
> ```
> time mflux-generate
> --prompt "Luxury food photograph"
> --model schnell
> --steps 2
> --seed 2
> --height 1024
> --width 1024
> ```
> 
> i.e without any quantization, your total was `38.232 total`. On a repeated run, do you get similar values? (I guess I was expecting your setup to beat the M4 Pro with half the memory as provided by @Stoobs in this issue, but maybe there are other details that come into play here...)
> 
> Just as a reference, [a similar setup to yours](https://gist.github.com/awni/a67d16d50f0f492d94a10418e0592bde?permalink_comment_id=5286033#gistcomment-5286033) get around 18 seconds for the non quantised run.
> 
> I also just added a [command](https://github.com/filipstrand/mflux?tab=readme-ov-file#%EF%B8%8F-image-generation-speed-updated) in the README which you can run to find out the exact number of CPU/GPU cores on your machine.


I ran again and it seems to match @ivanfioravant's result, total time takes ~20s with several iterations. I initially thought it could be due to system temperature; but even CPU temperature range from 41C - 63C the total time is still roughly around 19-21s:

**Normal run: 18.994 total**

```
time mflux-generate \
--prompt "Luxury food photograph" \
--model schnell \
--steps 2 \
--seed 2 \
--height 1024 \
--width 1024
Fetching 8 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 24403.22it/s]
Fetching 7 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 14926.35it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  7.00s/it]
mflux-generate --prompt "Luxury food photograph" --model schnell --steps 2  2  1.88s user 11.63s system 71% cpu 18.994 total

```

**quantized run: 20.752 total**
```

 time mflux-generate \
--prompt "Luxury food photograph" \
--model schnell \
--steps 2 \
--seed 2 \
--height 1024 \
--width 1024 \
--quantize 8
Fetching 8 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 13491.93it/s]
Fetching 7 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 12320.66it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:16<00:00,  8.14s/it]
mflux-generate --prompt "Luxury food photograph" --model schnell --steps 2  2  1.91s user 8.18s system 48% cpu 20.752 total
```

Quanitized and non-quantized seems to have similar generation time


_Also my bad; previously I thought the 'user' figure was the reference benchmark time, since it have the seconds unit, ie 11.63's'; I didn't realize the '18.994 total' was the actual true total time used in the benchmarks_  

**system_profiler SPHardwareDataType SPDisplaysDataType**


```

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac16,5
      Model Number: 
      Chip: Apple M4 Max
      Total Number of Cores: 16 (12 performance and 4 efficiency)
      Memory: 128 GB

Graphics/Displays:

    Apple M4 Max:

      Chipset Model: Apple M4 Max
      Type: GPU
      Bus: Built-In
      Total Number of Cores: 40
      Vendor: Apple (0x106b)
      Metal Support: Metal 3
```

**Comment by filipstrand** [comment]
@kasnol Thanks for running the benchmarks again! Great that the results matched  :)
